export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
export const DECREASE_AMOUNT = 'DECREASE_AMOUNT';
export const SET_LOADING = 'SET_LOADING';
export const DISPLAY_ITEMS = 'DISPLAY_ITEMS';
